### ISSUE TITLE
Define first upload start dates format

### ISSUE THREAD

**Issue by freefri** [oreplay/desktop-client#1]
POST to `/api/v1/events/{eventID}/stages/{stageID}/uploads/`

Example json to modify

```
[
   {
      "first_name":"Imported",
      "last_name":"Runner",
      "runner_results":{
         "start_time":"2024-01-02T11:00:00+00:00"
      }
   },
   {
      "first_name":"Imported",
      "last_name":"Second",
      "runner_results":{
         "start_time":"2024-01-02T11:01:00+00:00"
      }
   }
]
```

**Comment by jarufe** [comment]
As we recently discussed, a priori I would prefer not to change the values that are exported by OE and SiTiming. They don't include an UTC value as their events don't use this concept. So, I would prefer to keep the same value in the XML to JSON conversion and let the server make the calculations. So, an example of value is: 2024-01-02T11:01:00.000
